### ISSUE TITLE
CPU频率控制插件

### ISSUE THREAD

**Issue by VwEl** [paniy/nanopi-openwrt#8]
CPU频率控制插件有包能在其他固件上安装嘛?

**Comment by paniy** [comment]
编译时添加这两个项目即可：
https://github.com/paniy/R2S-R4S-X86-OpenWrt/trunk/PATCH/duplicate/luci-app-cpulimit
https://github.com/immortalwrt/immortalwrt/branches/master/package/ntlf9t/cpulimit
